meta_product_name: "Save My Wallet"
meta_title: "Save My Wallet - an application to help you to manage your money through a city game build !"
meta_description: "Save My Wallet is an application to manage daily expenses thanks to a user-friendly interface. /
The application is based on a city game build in order to help you to manage your money."
meta_image: "cover.png"
# required for Twitter Cards
